### ISSUE TITLE
"There should be one obvious way to do it"

### ISSUE THREAD

**Issue by keleshev** [tomerfiliba/construct3#1]
Maybe I should have written this to the user-group, but sorry, I don't like user groups :-)

I'm very impressed by construct3, and it's a pity that I didn't hear about construct1 and construct2 before. It would have saved me and my colleagues a ton of work a year ago.

But allow me to quote The Zen of Python:

> There should be one-- and preferably only one --obvious way to do it.

I think this is a very important rule of API design. When you have aliases and multiple syntaxes to accomplish the same thing things get confusing.

For example `byte`, `int8u` and `int8ul` mean the same, right? At the same time `int8`, `int8s`, `int8l` and `int8sl` are the same thing as well. You might disagree with me, but I think that's "too many ways to do it".
(Not mentioning that unsigned int8 is usually called `uint8`, not `int8u`).

You have a couple of syntax shortcuts as well: `byte[4]` for `Array(4, byte)`, `'a' / byte` for `('a', byte)`, and `byte >> byte` for `Struct(byte, byte)`. IMHO those are unnecessary. Compare:

``` python
'a' / byte >> 'b' / byte >> 'c' / byte >> 'd' / byte
Struct(('a', int8u), ('b', int8u), ('c', int8u), ('d', int8u))
```

The later one is only _marginally_ longer, but _how much more readable_ to me.

Anyway, I think construct3 is fantastic, great work! I'm sure it's impossible to spoil it—that's how good it is :-)

**Comment by tomerfiliba** [comment]
Thanks for the feedback! At the moment, nothing is finalized and there's still way to go. That's exactly why I wanted to bring this to discussion with the community.

I'll give you my take on it, but anyone is welcome to join the discussion:
- aliases are cheap and painless; there may be too many of them at the moment, so it's likely some of them will be removed before the final release, but 
- you should think of construct as a in-language DSL. many languages like Haskell and Scala have built-in support for this, while in the Python world it's quite rare, but DSLs are a good thing. especially when construct 3 is going to be compiled, you should think of the definition of data structures as a different language although it's contained in the same file as your python code. 
- i completely agree that the "multiline" version is more pythonic, and it's quite possible i'll drop `>>`, but the subscript notation and "slash operator" are more than just "stylistic choices". too many parentheses are a real problem, as exemplified by LISP and scheme. consider large data structures [such as these](https://github.com/construct/construct/blob/master/construct/formats/graphics/png.py) - having tuples everywhere would cripple the code. i find the slash readable and "worthwhile", but any other operator is just as good. as for the syntactic sugar for arrays -- it's much more convenient and familiar this way. also, and that's the real gem, you can use slices instead, e.g., `byte[4]` means an array of 4 bytes, while `byte[4:8]` means "a range of at least 4 bytes, up to 8". of course you can use any contextual expression instead of constants, or just omit one end, e.g., `byte[4:]` -- i find this very pythonic actually. in construct 2 we have `GreedyRepeater` (at least one element) and `OptionalGreedyRepeater` (zero or more elements); using slicing, we can neglect all these specialized constructs.

but again, nothing is finalized as of yet.

**Comment by keleshev** [comment]
1) Ok, what about the following syntax for sequences:

You know that strings allow the following operations:

``` python
4 * 'a' + 4 * 'b' + 2 * 'c' => 'aaaabbbbcc'
```

Binary data (and patters) are somewhat similar to strings, why not allow:

``` python
4 * uint8 + 4 * int8 + 2 * float32 => Sequence(uint8, uint8, uint8, uint8, int8, int8, int8, int8, float32, float32)
```

Maybe `+` makes more sense in this case than `>>`?

I understand the flexibility of `byte[4:8]` notation, though.

2) And maybe something along the lines of construct2 for structs:

``` python
Struct(int8.first_byte, uint8.second_byte)
Struct(int8['first-byte'], uint8['second-byte'])
Struct(int8('first-byte'), unit8('second-byte'))
```

**Comment by tomerfiliba** [comment]
addition is taken to be commutative, but here a + b != b + a. it's true that strings work that way, but then again string formatting operators (`%` or `format`) are preferred to this.

i had thoughts about using multiplication for arrays, but as i explained, slices are a necessary feature. besides, C uses subscripts for arrays, which is quite familiar:

```
struct foo {
    int bar;
    char data[100];
}
```

the `>>` operator also comes from C (C++ actually), as in `cout << "foo" << bar << "\n";`. on the other hand, i'm not sure it's a useful at all; perhaps an explicit `Struct()` or `Sequence()` would be better.

as for the `/` operator, i need to think about it some more. thanks for the input.
